matrix:
- name: Markdown
  sources:
    - '*.md'
    - 'docs/*.md'
  default_encoding: utf-8
  dictionary:
    wordlists:
      - .github/wordlist.txt
    encoding: utf-8
  pipeline:
    # Strip out Markdown noise (code blocks, links, etc.)
    - pyspelling.filters.markdown
    # Strip out HTML tags/attributes inside Markdown
    - pyspelling.filters.html
  aspell:
    lang: en
    d: en_US
    ignore-case: true
    run-together: true
